### ISSUE TITLE
Validation of choices with titles fails?

### ISSUE THREAD

**Issue by fledman** [bhch/react-json-form#102]
Given an array schema with choices, if the choices have titles, validation fails with `Invalid choice + "<value of first selected item>"`

I have made a simplified demonstration using the [validation section of the playground](https://bhch.github.io/react-json-form/playground/#18-validation)

enter this schema:
```
{
  "title": "Press \"Submit\" to validate data",
  "type": "array",
  "items": {
    "type": "string",
    "choices": [
      {"value": "RED", "title": "Thing One"},
      {"value": "BLUE", "title": "Thing Two"},
      {"value": "GREEN", "title": "Who Knows?"}
    ]
  },
  "minItems": 1,
  "uniqueItems": true
}
```
Validation submission fails like this:
<img width="1186" alt="Screenshot 2024-10-07 at 2 40 35 PM" src="https://github.com/user-attachments/assets/61d2903a-4398-4b22-a55b-25c68ce4c1fd">

However, if the titles are removed and we just have an array of choices, then it submits fine:
```
{
  "title": "Press \"Submit\" to validate data",
  "type": "array",
  "items": {
    "type": "string",
    "choices": ["RED", "BLUE", "GREEN"]
  },
  "minItems": 1,
  "uniqueItems": true
}
```
<img width="1226" alt="Screenshot 2024-10-07 at 2 39 39 PM" src="https://github.com/user-attachments/assets/eee4f8d2-0afc-409b-98ac-c28dd3a7005a">

**Comment by bhch** [comment]
Fixed in [v2.14.3](https://github.com/bhch/react-json-form/releases/tag/v2.14.3).

Also released in [django-jsonform v2.23.1](https://github.com/bhch/django-jsonform/releases/tag/v2.23.1).

Thanks for reporting.
