### ISSUE TITLE
Provide a simple file input widget for file-url uploads

### ISSUE THREAD

**Issue by bhch** [bhch/react-json-form#50]

**Comment by CearaWeir** [comment]
It is good if I can hide the "Choose from library". When I use "[File url](https://django-jsonform.readthedocs.io/en/latest/guide/upload.html#file-url)" , is it possible to upload files directly? 
eg:
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/98027994/197385515-79702795-aa20-4439-ad62-5605e335d19f.png">

**Comment by bhch** [comment]
Currently, it's not possible. But I will provide an option to control this in a few days.

**Comment by CearaWeir** [comment]
OK. Thank you.

**Comment by bhch** [comment]
@CearaWeir I've provided a feature for using a simple file input for `file-url`. Use the `widget` keyword:

```diff
{
    'type': 'string',
    'format': 'file-url',
+   'widget': 'fileinput'
}
```
[See live demo in playground](https://bhch.github.io/react-json-form/playground/#9-file-inputs).

This feature is released in:

 - [react-json-form v2.3.0](https://github.com/bhch/react-json-form/releases/tag/v2.3.0).
 - [django-jsonform v2.14.0](https://github.com/bhch/django-jsonform/releases/tag/v2.14.0).

Please upgrade. Thank you.
