### ISSUE TITLE
json-schema objects 'required' properties

### ISSUE THREAD

**Issue by gersmann** [bhch/react-json-form#56]
Hi @bhch, thank you for the awesome lib. One thing I noticed, which is a bit of a problem at the moment. The 'required' properties of the json-schema objects are not considered during validation. Just a custom 'required: true' flag at the property level.
https://json-schema.org/understanding-json-schema/reference/object.html#required-properties

Was this done on purpose? Without that validation, it's a bit hard to use externally defined JSON Schemas (such as schemas generated with Pydantic), though it might be possible to customise the schema generator.

**Comment by bhch** [comment]
Hi, I'll try to include this in the next release.

In the meantime, if you're using the django app, you can write your custom validation logic: https://django-jsonform.readthedocs.io/en/latest/guide/validation.html#custom-validation

**Comment by bhch** [comment]
@gersmann I've released `required` properties in Django in [v2.16.0](https://github.com/bhch/django-jsonform/releases/tag/v2.16.0). Please update.

Thank you for reporting this issue.
