### ISSUE TITLE
Feature request: add collapsible functionality to array

### ISSUE THREAD

**Issue by hayach** [bhch/react-json-form#70]
It would be nice if you can add Collapsible functionality to arrays so you can hide or show its contents. Move up, move down and remove are useful actions and collapsible would be a great addition to it specifically in big array modifications.

**Comment by bhch** [comment]
That sounds useful. I'll try to get it out in the next release.

**Comment by PaolaCocciaNet** [comment]
It would be great especially for array containing complex objects with lots of fields!

**Comment by bhch** [comment]
This feature has been released in [react-json-form v2.12.0](https://github.com/bhch/react-json-form/releases/tag/v2.12.0) and [django-jsonform v2.20.0](https://github.com/bhch/django-jsonform/releases/tag/v2.20.0). Please upgrade and test it out.

Thank you.

**Comment by PaolaCocciaNet** [comment]
Is there a way to collapse the fields using javascript (I'm using it through django-json-form)? 
I'd like to present the form with all the fields collapsed and maybe save the user's preference.
Thanks for your great work!

**Comment by bhch** [comment]
@PaolaCocciaNet Currently, there's no way for programmatically collapsing the sections. Though I might add support for that in a future release. This will be tracked in #89. I suggest you subscribe to that issue to stay in the loop.
