### ISSUE TITLE
Making a form readonly

### ISSUE THREAD

**Issue by corradio** [bhch/react-json-form#77]
Hello,

I have a use case where I'd like to make the whole form readonly, similarly to what [this library](https://rjsf-team.github.io/react-jsonschema-form/) does when one clicks "Disable whole form". It would be useful for read-only users.
Would be that be achievable?

Related note: it seems like it's not possible to set `readonly` to an array in order to prohibit them from adding new items.

**Comment by bhch** [comment]
> I have a use case where I'd like to make the whole form readonly

Okay I like the idea.

I'm assuming you will want to change this option dynamically on per request basis?

Only place it can be done dynamically is at the form field's widget level. This can't be an option at the model field.

If you have other ideas, let me know.

---

Support for `readOnly` on arrays will be tracked in #78.

**Comment by corradio** [comment]
> I'm assuming you will want to change this option dynamically on per request basis?

Correct.

> Only place it can be done dynamically is at the form field's widget level. This can't be an option at the model field.

This seems like a good solution. Let me know if/how I can help

**Comment by bhch** [comment]
Released in [react-json-form v2.10.0](https://github.com/bhch/django-jsonform/releases/tag/v2.19.0).

For Django, released in [django-jsonform v2.19.0](https://github.com/bhch/django-jsonform/releases/tag/v2.19.0). Please upgrade and test it out.

Thank you.

Thank you.

**Comment by corradio** [comment]
Works like a charm. Thanks!
