### ISSUE TITLE
Fix typo in react-json-form in case value > maximum

### ISSUE THREAD

**Issue by AlbanPadam** [bhch/react-json-form#84]
Hey,
Thanks for maintaining this repository and django-jsonform. 
I found a little typo [there](https://github.com/bhch/react-json-form/blob/640c57278f5bb5ba957b4f9b98c72dee74968582/dist/react-json-form.modern.js#L4068C108-L4068C108.)  (same for other files in dist).
It should be:
> 'This value must not be greater than ' + schema.maximum)

**Comment by bhch** [comment]
Thank you for reporting this. I'll release the fix soon.

**Comment by bhch** [comment]
Fix released in [react-json-form v2.11.1](https://github.com/bhch/react-json-form/releases/tag/v2.11.1) and in [django-jsonform v2.19.1](https://github.com/bhch/django-jsonform/releases/tag/v2.19.1).

Please upgrade and test it out.

Thank you.

**Comment by AlbanPadam** [comment]
It's good now thanks :+1:
