### ISSUE TITLE
Validation failure on schema with "oneOf" or "anyOf"

### ISSUE THREAD

**Issue by captain828** [bhch/react-json-form#99]
**Steps to reproduce:**
1. copy the schema from https://bhch.github.io/react-json-form/playground/#20-oneof (or from the anyOf example)
2. paste the schema into https://bhch.github.io/react-json-form/playground/#18-validation
3. click Submit

**Current result:**
```
Unsupported type "undefined" for object properties (keys).
```

**Expected result:**
The object should either be correctly validated against the schema or not give an unexpected error.

**Comment by captain828** [comment]
Awesome! ❤️ 

When do you think this will be released?
Also, when do you this will be merged with django-jsonform?

**Comment by bhch** [comment]
I'll try to get it out today.
